name: Emoji Application

on: 
  push: 
    branches: 
      - master
  pull_request: 
    branches:
      - master

jobs:

  build:
    name: Running Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '16'
      
      - name: Install npm
        run: npm ci

      - name: Building
        run: npm run build

      - name: Upload production-ready build files
        uses: actions/upload-artifact@v2
        with:
          name: production-files
          path: ./build
  
  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'

    steps:
    - name: Download artifact
      uses: actions/download-artifact@v2
      with:
        name: production-files
        path: ./build
        
    - name: Deploy artifact
      uses: jsmrcaga/action-netlify-deploy@v1.1.0
      with:
        NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_ACCES_TOKEN }}
        NETLIFY_SITE_ID:  ${{ secrets.NETLIFY_SITE_ID }}
        build_command: "echo hello"
        install_command: "echo hello"
        NETLIFY_DEPLOY_TO_PROD: true